#!/bin/bash

if xrandr | grep "HDMI1 disconnected"; then
    xrandr --output LVDS1 --auto
else
    xrandr --output HDMI1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output LVDS1 --off --output VGA1 --mode 1920x1080 --pos 1920x0 --rotate normal
fi
