---
include:
- "features/step_definitions/*.rb"
- "features/support/**/*.rb"
- "testsuite/ext-tools/*.rb"
- "testsuite/features/step_definitions/*.rb"
- "testsuite/features/support/**/*.rb"
exclude:
- spec/**/*
- test/**/*
- vendor/**/*
- ".bundle/**/*"
require: []
domains: []
reporters:
- rubocop
- require_not_found
formatter:
  rubocop:
    cops: safe
    except: []
    only: []
    extra_args: []
require_paths: []
plugins: []
max_files: 5000
